SELECT 
    TRANSACTIONS_PRODUCT_NAME2,
    COUNT(*) AS TOTAL_SOLD
FROM {{ ref('fct_transactions') }}
    WHERE TRANSACTIONS_STATUS = 'accepted'
GROUP BY TRANSACTIONS_PRODUCT_NAME2
ORDER BY TOTAL_SOLD DESC
LIMIT 10
