{{
  config(
    materialized = 'ephemeral'
    )
}}

WITH raw_transactions AS (
    SELECT
        *
    FROM
        SELLERX.RAW.RAW_TRANSACTIONS
)
SELECT
    ID AS TRANSACTIONS_ID,
	DEVICE_ID AS TRANSACTIONS_DEVICE_ID,
	PRODUCT_NAME AS TRANSACTIONS_PRODUCT_NAME,
	PRODUCT_SKU AS TRANSACTIONS_PRODUCT_SKU,
	PRODUCT_NAME2 AS TRANSACTIONS_PRODUCT_NAME2,
	AMOUNT AS TRANSACTIONS_AMOUNT,
	STATUS AS TRANSACTIONS_STATUS,
	CARD_NUMBER AS TRANSACTIONS_CARD_NUMBER,
	CVV AS TRANSACTIONS_CVV,
	CREATED_AT,
	HAPPENED_AT	
FROM
    raw_transactions