
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SELLERX;
USE SCHEMA SELLERX.RAW;

CREATE TABLE IF NOT EXISTS SELLERX.RAW.RAW_STORE (
    ID           STRING,
    NAME         STRING,
    ADDRESS      STRING,
    CITY         STRING,
    COUNTRY      STRING,
    CREATED_AT   TIMESTAMP_NTZ,
    TYPOLOGY     STRING,
    CUSTOMER_ID  STRING
);

CREATE TABLE IF NOT EXISTS SELLERX.RAW.RAW_TRANSACTIONS (
    ID             STRING,
    DEVICE_ID      STRING,
    PRODUCT_NAME   STRING,
    PRODUCT_SKU    STRING,
    AMOUNT         NUMBER(18, 2),
    STATUS         STRING,
    CARD_NUMBER    STRING,
    CVV            STRING,
    CREATED_AT     TIMESTAMP_NTZ,
    HAPPENED_AT    TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SELLERX.RAW.RAW_DEVICE (
    ID        STRING,
    TYPE      STRING,
    STORE_ID  STRING
);

REMOVE @SELLERX.STAGE.DEVICE_STAGE/device.csv;
REMOVE @SELLERX.STAGE.STORE_STAGE/store.csv;
REMOVE @SELLERX.STAGE.TRANSACTION_STAGE/transaction.csv;

DELETE FROM SELLERX.RAW.RAW_DEVICE;
SELECT COUNT (1) FROM SELLERX.RAW.RAW_DEVICE;

DELETE FROM SELLERX.RAW.RAW_STORE;
SELECT COUNT (1) FROM SELLERX.RAW.RAW_STORE;

DELETE FROM SELLERX.RAW.RAW_TRANSACTIONS;
SELECT COUNT (1) FROM SELLERX.RAW.RAW_TRANSACTIONS;

DROP TABLE SELLERX.RAW.RAW_DEVICE;
DROP TABLE SELLERX.STAGE.RAW_STORE;
DROP TABLE SELLERX.RAW.RAW_TRANSACTIONS;


COPY INTO SELLERX.RAW.RAW_DEVICE
FROM @SELLERX.STAGE.DEVICE_STAGE/device.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
FORCE = TRUE;

COPY INTO SELLERX.RAW.RAW_TRANSACTIONS
FROM @SELLERX.STAGE.TRANSACTION_STAGE/transaction.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
FORCE = TRUE;


COPY INTO SELLERX.RAW.RAW_STORE
FROM @SELLERX.STAGE.STORE_STAGE/store.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;