USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SELLERX;
USE SCHEMA SELLERX.DEV;

SELECT * FROM SRC_STORE;
SELECT * FROM SRC_DEVICE;
SELECT * FROM SRC_TRANSACTIONS;

SELECT * FROM DIM_STORE;
SELECT * FROM DIM_DEVICE;
SELECT * FROM FCT_TRANSACTIONS;


DROP VIEW IF EXISTS SRC_DEVICE;
DROP VIEW IF EXISTS SRC_STORE;
DROP VIEW IF EXISTS SRC_TRANSACTIONS;



SELECT COUNT (1) FROM 
    SELLERX.RAW.RAW_STORE;
    --100

SELECT COUNT (1) FROM 
    SELLERX.RAW.RAW_DEVICE;
    --200

SELECT COUNT (1) FROM 
    SELLERX.RAW.RAW_TRANSACTIONS;
    --1500
    
SELECT COUNT (1) FROM 
    SELLERX.DEV.DIM_STORE;
DELETE FROM SELLERX.DEV.DIM_STORE;

SELECT COUNT (1) FROM 
    SELLERX.DEV.DIM_DEVICE;
DELETE FROM SELLERX.DEV.DIM_DEVICE;

SELECT COUNT (1) FROM 
    SELLERX.DEV.FCT_TRANSACTIONS;
DELETE FROM SELLERX.DEV.FCT_TRANSACTIONS;

DROP VIEW IF EXISTS TOP_10_STORES;